(define (tri x y)
	(cond ((= y 1) 1)
		  ((= x y) 1)
		  (else (+ (tri (- x 1) (- y 1)) (tri (- x 1) y)))))
(define (print x y)
	(cond ((<= y x)
		(display (tri x y))
		(print x (+ 1 y)))))
(define (tri-line n)
	(if (> n 0)
		(tri-line (- n 1)))
	(print n 1)
	(display "\n"))