(define (fast-multi a b)
	(define (double n)
		(+ n n))
	(define (halve n)
		(/ n 2))
	(define (even? n)
		(= (remainder n 2) 0))
	(define (fast-multi-iter a b n)
		(cond ((= 0 b) n)
			((even? b) (fast-multi-iter (double a) (halve b) n))
			(else (fast-multi-iter a (- b 1) (+ n a)))))
	(fast-multi-iter a b 0))