(define (lookup given-key tree)
  (cond ((null? tree) false)
        ((= given-key (key (entry tree))) (entry tree))
        ((< given-key (key (entry tree))) (lookup given-key (left-branch tree)))
        (else (lookup given-key (right-branch tree)))))
